set enc=utf-8
set nocompatible
filetype off

" basic setting
set expandtab
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set nu
set hls
set cursorline
set cindent
set ignorecase
set list
set listchars=tab:>-,trail:·
filetype indent on
filetype plugin on
filetype plugin indent on

" set encoding
set encoding=utf8
set fileencodings=utf8,gb2312,gb18030,ucs-bom,latin1
set t_Co=256
syntax enable

" close position
au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

" vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" required!
Bundle "gmarik/vundle"

" 目录树形展示
Bundle "scrooloose/nerdtree"
let NERDTreeHighlightCursorline=1

" 顶上的多文件tab
Bundle "fholgado/minibufexpl.vim"
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1
let g:miniBufExplMoreThanOne=0

" 错误监测插件
Bundle "scrooloose/syntastic"

" 底下的 Powerline
Bundle "Lokaltog/vim-powerline"
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show Unicode glyphs
set t_Co=256 " Explicitly tell Vim that the terminal supports 256 colors

" Solarized 主题
Bundle "altercation/vim-colors-solarized"
set background=dark
colorscheme solarized

" Markdown
Bundle 'plasticboy/vim-markdown'
let g:vim_markdown_folding_disabled=1

" 神级插件，ZenCoding可以让你以一种神奇而无比爽快的感觉写HTML、CSS
Bundle 'ZenCoding.vim'

" smali 语法高亮
Bundle 'alderz/smali-vim'

" 高亮一列
:set cc=81
:hi colorcolumn ctermbg=0
